version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GREETING=Hello from Docker Compose!
    depends_on:
      - redis
    # Optional: connect to Redis if you extend the app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # No config needed for basic usage 